
var event_info = [
    {
        id:1,
        icon:'assets/images/2306korablik.jpg',
        title: "Останній Кораблик Сезону",
        day:"23",
        month:"06",
        year:"2016",
        hour:"19",
        location:"р. Дніпро",
        is_charity:false,
        is_free:true,
        ticketlink:"",
        contact:""
    },
    {
        id:2,
        icon:'assets/images/Folk.jpg',
        title: "Благодійний Концерт Folk Jam",
        day:"19",
        month:"05",
        year:"2016",
        hour:"18",
        location:"4 корпус, НаУКМА",
        is_charity:true,
        is_free:true,
        ticketlink:"",
        contact:""
    },
    {
        id:3,
        icon:'assets/images/Kupala.jpg',
        title: "Могилянське Купала",
        day:"18",
        month:"06",
        year:"2016",
        hour:"11",
        location:"Селище Бобриця",
        is_charity:false,
        is_free:false,
        ticketlink:"",
        contact:""
    },
    {
        id:1,
        icon:'assets/images/2306korablik.jpg',
        title: "Останній Кораблик Сезону",
        day:"23",
        month:"06",
        year:"2016",
        hour:"19",
        location:"р. Дніпро",
        is_charity:false,
        is_free:true,
        ticketlink:"",
        contact:""
    },
    {
        id:2,
        icon:'assets/images/Folk.jpg',
        title: "Благодійний Концерт Folk Jam",
        day:"19",
        month:"05",
        year:"2016",
        hour:"18",
        location:"4 корпус, НаУКМА",
        is_charity:true,
        is_free:true,
        ticketlink:"",
        contact:""
    },
    {
        id:3,
        icon:'assets/images/Kupala.jpg',
        title: "Могилянське Купала",
        day:"18",
        month:"06",
        year:"2016",
        hour:"11",
        location:"Селище Бобриця",
        is_charity:false,
        is_free:false,
        ticketlink:"",
        contact:""
    },{
        id:1,
        icon:'assets/images/2306korablik.jpg',
        title: "Останній Кораблик Сезону",
        day:"23",
        month:"06",
        year:"2016",
        hour:"19",
        location:"р. Дніпро",
        is_charity:false,
        is_free:true,
        ticketlink:"",
        contact:""
    },
    {
        id:2,
        icon:'assets/images/Folk.jpg',
        title: "Благодійний Концерт Folk Jam",
        day:"19",
        month:"05",
        year:"2016",
        hour:"18",
        location:"4 корпус, НаУКМА",
        is_charity:true,
        is_free:true,
        ticketlink:"",
        contact:""
    },
    {
        id:3,
        icon:'assets/images/Kupala.jpg',
        title: "Могилянське Купала",
        day:"18",
        month:"06",
        year:"2016",
        hour:"11",
        location:"Селище Бобриця",
        is_charity:false,
        is_free:false,
        ticketlink:"",
        contact:""
    }
];

module.exports = event_info;